version: "3"

services:
  server:
    image: stevymonkam/backend1:1.0
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ecomerce?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=manounou
      - MYSQL_DATABASE=ecomerce
      - MYSQL_USER=stevy
      - MYSQL_PASSWORD=manounou
    volumes:
      - ./mysql-data:/var/lib/mysql  # Montage du volume local dans le conteneur MySQL

networks:
  springmysql-net:

